flowchart TB
    subgraph Subscription["Azure Subscription"]
        subgraph NetRG["RG-AZ104-Network"]
            VNet["VNet-AZ104-Enterprise<br/>10.10.0.0/16"]
            Mgmt["snet-management<br/>10.10.0.0/24"]
            Web["snet-workload<br/>10.10.1.0/24"]
            App["snet-app<br/>10.10.2.0/24"]
            Bastion["Azure Bastion<br/>Developer SKU"]
            NAT["NAT Gateway"]
            NSGs["Network Security Groups"]
            LAW["LAW-AZ104-Enterprise"]
            DCR["DCR-AZ104-Linux"]
            AG["AG-AZ104-Alerts"]
        end
        subgraph ComputeRG["RG-AZ104-COMPUTE"]
            MgmtVM["VM-AZ104-Management<br/>10.10.0.4"]
            WebVM["VM-AZ104-Web<br/>10.10.1.4<br/>Nginx"]
            AppVM["VM-AZ104-App<br/>10.10.2.4<br/>Python :8080<br/>No public IP"]
        end
        subgraph StorageRG["RG-AZ104-Storage"]
            SA["kishorestorage1<br/>Public access enabled"]
            DNS["Private DNS<br/>privatelink.blob.core.windows.net"]
            PE["PE-AZ104-Storage<br/>10.10.2.5"]
            Blob["application-files<br/>Private"]
        end
    end

    VNet --> Mgmt
    VNet --> Web
    VNet --> App
    Mgmt --> MgmtVM
    Web --> WebVM
    App --> AppVM
    Bastion --> MgmtVM
    NAT --> Web
    NSGs --> VNet

    WebVM -->|"TCP 8080"| AppVM
    MgmtVM -->|"TCP 22"| AppVM

    AppVM --> DNS
    DNS --> PE
    PE --> SA
    SA --> Blob

    MgmtVM --> DCR
    WebVM --> DCR
    AppVM --> DCR
    DCR --> LAW
    LAW --> AG
